name: seek_app

packages:
  - seek_app
  - packages/*
  - modules/*

scripts:
  analyze:
    exec: dart analyze .

  pub_upgrade:
    exec: flutter pub upgrade

  clean_project:
    run: find . -name pubspec.lock -delete && y | flutter pub cache clean && flutter pub get &&  dart pub global activate melos && melos bs
