targets:
  $default:
    sources:
      exclude:
        - example/**
    builders:
      pigeon_generator:
        options:
          inputs: pigeons
          dart:
            out: "lib/pigeons/"
            test_out: "test/pigeons/"
          swift:
            out: "ios/Classes"
          kotlin:
            out: "android/src/main/kotlin/com/example/seek_biometrics/pigeons"
            package: com.example.seek_biometrics

additional_public_assets:
  - pigeons/**
