platform :android do
  desc "Seek app"

  lane :distribute do
      # Build the app bundle.
      sh "flutter build appbundle --release -t lib/environments/main_prod.dart" 

      # Upload to Firebase App Distribution
      release = firebase_app_distribution(
        service_credentials_json_data: ENV['GOOGLE_APPLICATION_CREDENTIALS'],
        app: "1:1015820849617:android:ab5598680a5634882c90f0",
        groups: "seek-testers",
        release_notes: "App for seek interview",
        android_artifact_type: "AAB",
        android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab",
      )
  end
end