name: Flutter Firebase CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LC_ALL: en_US.UTF-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3" # Specify your ruby version here
      - name: Install Fastlane
        run: gem install fastlane
      - name: Install Fastlane Firebase App Distribution plugin
        working-directory: android
        run: fastlane add_plugin firebase_app_distribution
      - name: Configure Google Application Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcp-key.json

      - name: Run Fastlane for Android
        working-directory: android
        run: fastlane distribute
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
